### ISSUE TITLE
support for vanialla and custom media queries

### ISSUE THREAD

**Issue by antonk52** [antonk52/coc-cssmodules#7]
As of right now go-do-definition is broken for classnames that are located inside of media queries

Example

```js
import css from './style.css'

css.foo
//  ^ cannot jump to definition from here
```

```css
@media (min-width: 500px) {
  .foo {
    color: hotpink;
  }
}
```
